networks:
  tugtainer:
    driver: bridge
services:
  app:
    container_name: tugtainer
    build:
      context: https://github.com/Quenary/tugtainer.git#latest
    volumes:
      - tugtainer_data:/tugtainer
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "curl -f  http://localhost:8000/api/public/health || exit 1",
        ]
      interval: 10s
      start-period: 10
      timeout: 5s
      retries: 5
    networks:
      - tugtainer
    ports:
      - '9412:80'
volumes:
  tugtainer_data:
